### ISSUE TITLE
AI image recognition/description support

### ISSUE THREAD

**Issue by rugk** [Lynnesbian/OCRbot#5]
Maybe you could use some artificial intelligence to detect non-text images and describe them.

Problems:
* sometimes makes mistakes, but I guess you cannot prevent this
* you likely need to use a third-party service, I guess(?)

**Comment by Lynnesbian** [comment]
This is a nice feature to have, but it'd require vastly more processing power than I have available. Recognising images using neural networks (which is the best option available) requires using a powerful GPU (especially during the training stage, which can take *days* with a top of the range GPU), which I don't have.

Pre-trained datasets exist, but none that are openly accessible. For example, Facebook can recognise whether an image contains a tree, clouds, a face, etc., but whatever service they use to do it isn't openly available.

**Comment by Lynnesbian** [comment]
Ultimately, this might be possible one day if I ever gain access to a more powerful server than the one I have (4GB memory, 60GB storage, no GPU), but right now, it's sadly not doable.
